project:
  type: website
  output-dir: /Users/nikhitaairi/Desktop/nikhitaairi.github.io/

website:
  title: "Nikhita Airi"
  navbar:
    tools:
    - icon: github
      href: https://github.com/nikhitaairi
    - icon: linkedin
      href: https://www.linkedin.com/in/nikhita-airi 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Work"
        menu:
          - href: work.qmd
            text: "Writing & reports"
          - href: media.qmd
            text: "Media"
          - href: portfolio.qmd
            text: "Data viz"
  google-analytics: GOOGLE_ANALYTICS_MEASUREMENT_ID
  favicon: assets/favicon-32x32.png
          # - href: reports.qmd
          #   text: "Research areas"
          # - href: cv.qmd
          #   text: "Journal articles"
          # - href: media.qmd
          #   text: "Blogs/media"
      
        
  page-footer: 
    right: "Made with [Quarto](https://quarto.org)"
          
  back-to-top-navigation: false


format:
  html:
    theme:
      - brite #zephyr
      - assets/custom.scss
    css: "bootstrap.min-2.css"
    #css: styles.css
    toc: true

editor: visual

